(define (print-point p)
  (newline)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")"))

(define make-point cons)
(define x-point car)
(define y-point cdr)
(define make-segment cons)
(define start-segment car)
(define end-segment cdr)

(define (midpoint-segment s)
  (define (avg-2 x y) (/ (+ x y) 2))
  (let ((a (start-segment s)) (b (end-segment s)))
      (make-point (avg-2 (x-point a) (x-point b))
                  (avg-2 (y-point a) (y-point b)))))
